//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accion
    {
        public Accion()
        {
            this.Accion1 = new HashSet<Accion>();
            this.Rol_Accion = new HashSet<Rol_Accion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDPadre { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Accion> Accion1 { get; set; }
        public virtual Accion Accion2 { get; set; }
        public virtual ICollection<Rol_Accion> Rol_Accion { get; set; }
    }
}
