//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Centro
    {
        public Centro()
        {
            this.CentroTrabajador = new HashSet<CentroTrabajador>();
            this.PuestoTrabajador = new HashSet<PuestoTrabajador>();
            this.Paciente = new HashSet<Paciente>();
            this.Cita = new HashSet<Cita>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDUsuarioAdminitrador { get; set; }
        public int IDPlan { get; set; }
        public string CIF { get; set; }
        public string NombreCentro { get; set; }
        public string Descripcion { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public int IDProvincia { get; set; }
        public string Localidad { get; set; }
        public string CP { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string MotivoBaja { get; set; }
        public bool Activo { get; set; }
        public bool EsPresencial { get; set; }
        public bool EsOnline { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public int MaxTrabajadores { get; set; }
        public int TrabajadoresActuales { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<CentroTrabajador> CentroTrabajador { get; set; }
        public virtual ICollection<PuestoTrabajador> PuestoTrabajador { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual ICollection<Cita> Cita { get; set; }
    }
}
