//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID { get; set; }
        public int IDTipo { get; set; }
        public int IDTrabajador { get; set; }
        public int IDPaciente { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFin { get; set; }
        public string Titulo { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public int IDCentro { get; set; }
        public string NotasPrivadas { get; set; }
        public string PautasPaciente { get; set; }
        public bool Completada { get; set; }
    
        public virtual Centro Centro { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
