//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comida
    {
        public int ID { get; set; }
        public int IDDiario { get; set; }
        public int IDTipoComida { get; set; }
        public string Alimentos { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public System.DateTime Dia { get; set; }
    
        public virtual Diario Diario { get; set; }
        public virtual ComidaTipo ComidaTipo { get; set; }
    }
}
