//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diario
    {
        public Diario()
        {
            this.EstadoAnimicoDiario = new HashSet<EstadoAnimicoDiario>();
            this.Deporte1 = new HashSet<Deporte>();
            this.Comida = new HashSet<Comida>();
        }
    
        public int ID { get; set; }
        public int IDPaciente { get; set; }
        public System.DateTime Dia { get; set; }
        public Nullable<decimal> AguaCantidad { get; set; }
        public string Medicamentos { get; set; }
        public Nullable<bool> Menstruaccion { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> IDSuenyo { get; set; }
        public Nullable<int> IDEstado { get; set; }
        public bool Deporte { get; set; }
        public string ObsDeporte { get; set; }
        public Nullable<int> IDMedidas { get; set; }
    
        public virtual OpcionesDiarioTipo OpcionesDiarioTipo { get; set; }
        public virtual OpcionesDiarioTipo OpcionesDiarioTipo1 { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual ICollection<EstadoAnimicoDiario> EstadoAnimicoDiario { get; set; }
        public virtual ICollection<Deporte> Deporte1 { get; set; }
        public virtual ICollection<Comida> Comida { get; set; }
        public virtual PacienteMedidas PacienteMedidas { get; set; }
    }
}
