//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteMedidas
    {
        public PacienteMedidas()
        {
            this.Diario = new HashSet<Diario>();
        }
    
        public int ID { get; set; }
        public int IDPaciente { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> CmPecho { get; set; }
        public Nullable<decimal> CmCintura { get; set; }
        public Nullable<decimal> CmCadera { get; set; }
        public Nullable<decimal> PGrasa { get; set; }
        public Nullable<decimal> PMagro { get; set; }
        public Nullable<decimal> PAgua { get; set; }
        public System.DateTime PostedDate { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Diario> Diario { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
