//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        public Puesto()
        {
            this.PuestoTrabajador = new HashSet<PuestoTrabajador>();
            this.Cita = new HashSet<Cita>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string colorAgenda { get; set; }
    
        public virtual ICollection<PuestoTrabajador> PuestoTrabajador { get; set; }
        public virtual ICollection<Cita> Cita { get; set; }
    }
}
