//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuestoTrabajador
    {
        public int IDUsuario { get; set; }
        public int IDPuesto { get; set; }
        public int IDCentro { get; set; }
        public bool Activo { get; set; }
    
        public virtual Puesto Puesto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Centro Centro { get; set; }
    }
}
