//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        public Trabajador()
        {
            this.CentroTrabajador = new HashSet<CentroTrabajador>();
            this.Cita = new HashSet<Cita>();
        }
    
        public int IDUsuario { get; set; }
        public string NumSegSocial { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string DNI { get; set; }
        public string Nacionalidad { get; set; }
        public string Localidad { get; set; }
        public string Telefono { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<CentroTrabajador> CentroTrabajador { get; set; }
        public virtual ICollection<Cita> Cita { get; set; }
    }
}
