//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.PuestoTrabajador = new HashSet<PuestoTrabajador>();
            this.Centro = new HashSet<Centro>();
        }
    
        public int ID { get; set; }
        public int IDRol { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public int IDProvincia { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string CodigoRecuperacion { get; set; }
        public Nullable<System.DateTime> FechaCodigoRecuperacion { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual TrabajadoresNB TrabajadoresNB { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        public virtual ICollection<PuestoTrabajador> PuestoTrabajador { get; set; }
        public virtual ICollection<Centro> Centro { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
