//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class centros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal centros() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.centros", typeof(centros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Appointment.
        /// </summary>
        public static string agenda_1 {
            get {
                return ResourceManager.GetString("agenda_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit appointment.
        /// </summary>
        public static string agenda_10 {
            get {
                return ResourceManager.GetString("agenda_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save appointment.
        /// </summary>
        public static string agenda_11 {
            get {
                return ResourceManager.GetString("agenda_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add appointment.
        /// </summary>
        public static string agenda_12 {
            get {
                return ResourceManager.GetString("agenda_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Appointment type.
        /// </summary>
        public static string agenda_13 {
            get {
                return ResourceManager.GetString("agenda_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient.
        /// </summary>
        public static string agenda_14 {
            get {
                return ResourceManager.GetString("agenda_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Appointment title.
        /// </summary>
        public static string agenda_15 {
            get {
                return ResourceManager.GetString("agenda_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string agenda_16 {
            get {
                return ResourceManager.GetString("agenda_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time.
        /// </summary>
        public static string agenda_17 {
            get {
                return ResourceManager.GetString("agenda_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End time.
        /// </summary>
        public static string agenda_18 {
            get {
                return ResourceManager.GetString("agenda_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        public static string agenda_19 {
            get {
                return ResourceManager.GetString("agenda_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See previous appointment.
        /// </summary>
        public static string agenda_2 {
            get {
                return ResourceManager.GetString("agenda_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Legend.
        /// </summary>
        public static string agenda_20 {
            get {
                return ResourceManager.GetString("agenda_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guidelines.
        /// </summary>
        public static string agenda_21 {
            get {
                return ResourceManager.GetString("agenda_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back to schedule.
        /// </summary>
        public static string agenda_3 {
            get {
                return ResourceManager.GetString("agenda_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End appointment.
        /// </summary>
        public static string agenda_4 {
            get {
                return ResourceManager.GetString("agenda_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private notes.
        /// </summary>
        public static string agenda_5 {
            get {
                return ResourceManager.GetString("agenda_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient Guidelines.
        /// </summary>
        public static string agenda_6 {
            get {
                return ResourceManager.GetString("agenda_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Worker.
        /// </summary>
        public static string agenda_7 {
            get {
                return ResourceManager.GetString("agenda_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Previous appointment on.
        /// </summary>
        public static string agenda_8 {
            get {
                return ResourceManager.GetString("agenda_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete appointment.
        /// </summary>
        public static string agenda_9 {
            get {
                return ResourceManager.GetString("agenda_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you associated with any center?.
        /// </summary>
        public static string associated_center {
            get {
                return ResourceManager.GetString("associated_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add center.
        /// </summary>
        public static string btnAnyadir {
            get {
                return ResourceManager.GetString("btnAnyadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center&apos;s state.
        /// </summary>
        public static string center_state {
            get {
                return ResourceManager.GetString("center_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centers.
        /// </summary>
        public static string Centros {
            get {
                return ResourceManager.GetString("Centros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string form_Address {
            get {
                return ResourceManager.GetString("form_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF/NIF.
        /// </summary>
        public static string form_CIF {
            get {
                return ResourceManager.GetString("form_CIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultation.
        /// </summary>
        public static string form_Consultation {
            get {
                return ResourceManager.GetString("form_Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Workers.
        /// </summary>
        public static string form_currentWorkers {
            get {
                return ResourceManager.GetString("form_currentWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string form_Description {
            get {
                return ResourceManager.GetString("form_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director Center.
        /// </summary>
        public static string form_Director {
            get {
                return ResourceManager.GetString("form_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string form_Email {
            get {
                return ResourceManager.GetString("form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Face-to-face.
        /// </summary>
        public static string form_F2F {
            get {
                return ResourceManager.GetString("form_F2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        public static string form_Location {
            get {
                return ResourceManager.GetString("form_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Workers.
        /// </summary>
        public static string form_maxWorkers {
            get {
                return ResourceManager.GetString("form_maxWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string form_Name {
            get {
                return ResourceManager.GetString("form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string form_Online {
            get {
                return ResourceManager.GetString("form_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PC.
        /// </summary>
        public static string form_PC {
            get {
                return ResourceManager.GetString("form_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone.
        /// </summary>
        public static string form_Phone {
            get {
                return ResourceManager.GetString("form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscription.
        /// </summary>
        public static string form_Plan {
            get {
                return ResourceManager.GetString("form_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string form_State {
            get {
                return ResourceManager.GetString("form_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website.
        /// </summary>
        public static string form_Website {
            get {
                return ResourceManager.GetString("form_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this center?.
        /// </summary>
        public static string msgEliminar {
            get {
                return ResourceManager.GetString("msgEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Center.
        /// </summary>
        public static string newCenter {
            get {
                return ResourceManager.GetString("newCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activate center.
        /// </summary>
        public static string tablaActivar {
            get {
                return ResourceManager.GetString("tablaActivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deactivate center.
        /// </summary>
        public static string tablaDesactivar {
            get {
                return ResourceManager.GetString("tablaDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit center.
        /// </summary>
        public static string tablaEditar {
            get {
                return ResourceManager.GetString("tablaEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete center.
        /// </summary>
        public static string tablaEliminar {
            get {
                return ResourceManager.GetString("tablaEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string tablaEmail {
            get {
                return ResourceManager.GetString("tablaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string tablaNombre {
            get {
                return ResourceManager.GetString("tablaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan.
        /// </summary>
        public static string tablaPlan {
            get {
                return ResourceManager.GetString("tablaPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string tablaProvincia {
            get {
                return ResourceManager.GetString("tablaProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable Person.
        /// </summary>
        public static string tablaResponsable {
            get {
                return ResourceManager.GetString("tablaResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone.
        /// </summary>
        public static string tablaTelefono {
            get {
                return ResourceManager.GetString("tablaTelefono", resourceCulture);
            }
        }
    }
}
