//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class diario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal diario() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.diario", typeof(diario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add food.
        /// </summary>
        public static string anyadir_comida {
            get {
                return ResourceManager.GetString("anyadir_comida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. 5 foods allowed.
        /// </summary>
        public static string comida_nota {
            get {
                return ResourceManager.GetString("comida_nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have you practiced sport today?.
        /// </summary>
        public static string deporte_1 {
            get {
                return ResourceManager.GetString("deporte_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What sports have you practiced?.
        /// </summary>
        public static string deporte_2 {
            get {
                return ResourceManager.GetString("deporte_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations:.
        /// </summary>
        public static string deporte_3 {
            get {
                return ResourceManager.GetString("deporte_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to your personal nutrition diary.
        /// </summary>
        public static string diario_1 {
            get {
                return ResourceManager.GetString("diario_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Here you can enter the necessary information for your follow-up, all the information is totally optional.
        /// </summary>
        public static string diario_2 {
            get {
                return ResourceManager.GetString("diario_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See diary of the day.
        /// </summary>
        public static string diario_calendario {
            get {
                return ResourceManager.GetString("diario_calendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nutrition.
        /// </summary>
        public static string menu_alimentacion {
            get {
                return ResourceManager.GetString("menu_alimentacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Physical activity.
        /// </summary>
        public static string menu_deporte {
            get {
                return ResourceManager.GetString("menu_deporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measures.
        /// </summary>
        public static string menu_medidas {
            get {
                return ResourceManager.GetString("menu_medidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Health.
        /// </summary>
        public static string menu_salud {
            get {
                return ResourceManager.GetString("menu_salud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No food added yet.
        /// </summary>
        public static string no_comida {
            get {
                return ResourceManager.GetString("no_comida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How do you feel today?.
        /// </summary>
        public static string salud_1 {
            get {
                return ResourceManager.GetString("salud_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How is your mood?.
        /// </summary>
        public static string salud_2 {
            get {
                return ResourceManager.GetString("salud_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mark all the emotions you feel.
        /// </summary>
        public static string salud_3 {
            get {
                return ResourceManager.GetString("salud_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How much water have you drunk today?.
        /// </summary>
        public static string salud_4 {
            get {
                return ResourceManager.GetString("salud_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How did you sleep?.
        /// </summary>
        public static string salud_5 {
            get {
                return ResourceManager.GetString("salud_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Have you taken any medication?.
        /// </summary>
        public static string salud_6 {
            get {
                return ResourceManager.GetString("salud_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you on your period?.
        /// </summary>
        public static string salud_7 {
            get {
                return ResourceManager.GetString("salud_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string salud_71 {
            get {
                return ResourceManager.GetString("salud_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string salud_72 {
            get {
                return ResourceManager.GetString("salud_72", resourceCulture);
            }
        }
    }
}
