//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal forms() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.forms", typeof(forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string form_btn_cancel {
            get {
                return ResourceManager.GetString("form_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string form_btn_save {
            get {
                return ResourceManager.GetString("form_btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string form_btn_send {
            get {
                return ResourceManager.GetString("form_btn_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center or patient?:.
        /// </summary>
        public static string form_centerOrPatiente {
            get {
                return ResourceManager.GetString("form_centerOrPatiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comment:.
        /// </summary>
        public static string form_comment {
            get {
                return ResourceManager.GetString("form_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        public static string form_email {
            get {
                return ResourceManager.GetString("form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field is required.
        /// </summary>
        public static string form_fieldRequiredMsg {
            get {
                return ResourceManager.GetString("form_fieldRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string form_name {
            get {
                return ResourceManager.GetString("form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        public static string form_phone {
            get {
                return ResourceManager.GetString("form_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center.
        /// </summary>
        public static string form_rb_center {
            get {
                return ResourceManager.GetString("form_rb_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patient.
        /// </summary>
        public static string form_rb_patient {
            get {
                return ResourceManager.GetString("form_rb_patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fields marked with * are required.
        /// </summary>
        public static string form_requiredFields {
            get {
                return ResourceManager.GetString("form_requiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initial form.
        /// </summary>
        public static string initialForm {
            get {
                return ResourceManager.GetString("initialForm", resourceCulture);
            }
        }
    }
}
