//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class menuZonaPrivada {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal menuZonaPrivada() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.menuZonaPrivada", typeof(menuZonaPrivada).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schedule.
        /// </summary>
        public static string agenda {
            get {
                return ResourceManager.GetString("agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current center.
        /// </summary>
        public static string centroActual {
            get {
                return ResourceManager.GetString("centroActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string centroActualCambiar {
            get {
                return ResourceManager.GetString("centroActualCambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change center.
        /// </summary>
        public static string centroCambiarCambiar {
            get {
                return ResourceManager.GetString("centroCambiarCambiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the center you want to view.
        /// </summary>
        public static string centroCambiarMsg {
            get {
                return ResourceManager.GetString("centroCambiarMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centers.
        /// </summary>
        public static string centros {
            get {
                return ResourceManager.GetString("centros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collapse menu.
        /// </summary>
        public static string colapsarMenu {
            get {
                return ResourceManager.GetString("colapsarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diary.
        /// </summary>
        public static string diario {
            get {
                return ResourceManager.GetString("diario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expand menu.
        /// </summary>
        public static string expandirMenu {
            get {
                return ResourceManager.GetString("expandirMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My center.
        /// </summary>
        public static string mi_centro {
            get {
                return ResourceManager.GetString("mi_centro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patients.
        /// </summary>
        public static string pacientes {
            get {
                return ResourceManager.GetString("pacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My data.
        /// </summary>
        public static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string perfil_datos {
            get {
                return ResourceManager.GetString("perfil_datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prices.
        /// </summary>
        public static string perfil_precios {
            get {
                return ResourceManager.GetString("perfil_precios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promotions.
        /// </summary>
        public static string perfil_promo {
            get {
                return ResourceManager.GetString("perfil_promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Staff.
        /// </summary>
        public static string personal {
            get {
                return ResourceManager.GetString("personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progress of the month.
        /// </summary>
        public static string resumen {
            get {
                return ResourceManager.GetString("resumen", resourceCulture);
            }
        }
    }
}
