//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class paciente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal paciente() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.paciente", typeof(paciente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First of all, what is your main goal?.
        /// </summary>
        public static string p_basic_1 {
            get {
                return ResourceManager.GetString("p_basic_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gain weight.
        /// </summary>
        public static string p_basic_11 {
            get {
                return ResourceManager.GetString("p_basic_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lose weight.
        /// </summary>
        public static string p_basic_12 {
            get {
                return ResourceManager.GetString("p_basic_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Improve my health.
        /// </summary>
        public static string p_basic_13 {
            get {
                return ResourceManager.GetString("p_basic_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What lifestyle do you currently lead?.
        /// </summary>
        public static string p_basic_2 {
            get {
                return ResourceManager.GetString("p_basic_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sedentary.
        /// </summary>
        public static string p_basic_21 {
            get {
                return ResourceManager.GetString("p_basic_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string p_basic_22 {
            get {
                return ResourceManager.GetString("p_basic_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you often suffer from stress or anxiety?.
        /// </summary>
        public static string p_basic_3 {
            get {
                return ResourceManager.GetString("p_basic_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string p_basic_31 {
            get {
                return ResourceManager.GetString("p_basic_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string p_basic_32 {
            get {
                return ResourceManager.GetString("p_basic_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you feel bad about your physical appearance?.
        /// </summary>
        public static string p_basic_4 {
            get {
                return ResourceManager.GetString("p_basic_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string p_Btb_Back {
            get {
                return ResourceManager.GetString("p_Btb_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish.
        /// </summary>
        public static string p_Btn_End {
            get {
                return ResourceManager.GetString("p_Btn_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string p_Btn_Next {
            get {
                return ResourceManager.GetString("p_Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Let&apos;s go!.
        /// </summary>
        public static string p_Btn_Start {
            get {
                return ResourceManager.GetString("p_Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In order to help you we need to know some information about you.
        /// </summary>
        public static string p_Inicial_Msg1 {
            get {
                return ResourceManager.GetString("p_Inicial_Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good job! Confirm the data sending to finish.
        /// </summary>
        public static string p_Inicial_Msg2 {
            get {
                return ResourceManager.GetString("p_Inicial_Msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This part is totally optional, record your measurements only if you wish.
        /// </summary>
        public static string p_Inicial_Msg3 {
            get {
                return ResourceManager.GetString("p_Inicial_Msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height (cm).
        /// </summary>
        public static string p_measure_1 {
            get {
                return ResourceManager.GetString("p_measure_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual weight (kg).
        /// </summary>
        public static string p_measure_2 {
            get {
                return ResourceManager.GetString("p_measure_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your current BMI is: .
        /// </summary>
        public static string p_measure_3 {
            get {
                return ResourceManager.GetString("p_measure_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Measurements (cm).
        /// </summary>
        public static string p_measure_4 {
            get {
                return ResourceManager.GetString("p_measure_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chest.
        /// </summary>
        public static string p_measure_41 {
            get {
                return ResourceManager.GetString("p_measure_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waist.
        /// </summary>
        public static string p_measure_42 {
            get {
                return ResourceManager.GetString("p_measure_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hip.
        /// </summary>
        public static string p_measure_43 {
            get {
                return ResourceManager.GetString("p_measure_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other measures (%).
        /// </summary>
        public static string p_measure_5 {
            get {
                return ResourceManager.GetString("p_measure_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Fat.
        /// </summary>
        public static string p_measure_51 {
            get {
                return ResourceManager.GetString("p_measure_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Muscle.
        /// </summary>
        public static string p_measure_52 {
            get {
                return ResourceManager.GetString("p_measure_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Water.
        /// </summary>
        public static string p_measure_53 {
            get {
                return ResourceManager.GetString("p_measure_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you...?.
        /// </summary>
        public static string p_sex_1 {
            get {
                return ResourceManager.GetString("p_sex_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string p_sex_11 {
            get {
                return ResourceManager.GetString("p_sex_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string p_sex_12 {
            get {
                return ResourceManager.GetString("p_sex_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to NutriBuddy.
        /// </summary>
        public static string p_TitleInicial {
            get {
                return ResourceManager.GetString("p_TitleInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Days you have done a physical activity.
        /// </summary>
        public static string pz_deporte {
            get {
                return ResourceManager.GetString("pz_deporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emotion of the month.
        /// </summary>
        public static string pz_emocion {
            get {
                return ResourceManager.GetString("pz_emocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This month above all you are.
        /// </summary>
        public static string pz_emocion_msg {
            get {
                return ResourceManager.GetString("pz_emocion_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To update these data you must complete the nutrition diary.
        /// </summary>
        public static string pz_instruccion {
            get {
                return ResourceManager.GetString("pz_instruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data for this month yet.
        /// </summary>
        public static string pz_noinfo {
            get {
                return ResourceManager.GetString("pz_noinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Summary.
        /// </summary>
        public static string pz_resumen {
            get {
                return ResourceManager.GetString("pz_resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string pz_sex {
            get {
                return ResourceManager.GetString("pz_sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next appointment in.
        /// </summary>
        public static string pz_sigcita_1 {
            get {
                return ResourceManager.GetString("pz_sigcita_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a with.
        /// </summary>
        public static string pz_sigcita_2 {
            get {
                return ResourceManager.GetString("pz_sigcita_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sleep quality of the month.
        /// </summary>
        public static string pz_suenyo {
            get {
                return ResourceManager.GetString("pz_suenyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No sleep information.
        /// </summary>
        public static string pz_suenyo_404 {
            get {
                return ResourceManager.GetString("pz_suenyo_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are sleeping great, good job!.
        /// </summary>
        public static string pz_suenyo_bien {
            get {
                return ResourceManager.GetString("pz_suenyo_bien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oh no! You have to try to improve your quality of sleep, cheer up!.
        /// </summary>
        public static string pz_suenyo_mal {
            get {
                return ResourceManager.GetString("pz_suenyo_mal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are sleeping quite well, but you can improve.
        /// </summary>
        public static string pz_suenyo_regular {
            get {
                return ResourceManager.GetString("pz_suenyo_regular", resourceCulture);
            }
        }
    }
}
