//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of Birth.
        /// </summary>
        public static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private Zone.
        /// </summary>
        public static string btn_privatezone {
            get {
                return ResourceManager.GetString("btn_privatezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        public static string btn_recoverpass {
            get {
                return ResourceManager.GetString("btn_recoverpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + information.
        /// </summary>
        public static string home_section3_information {
            get {
                return ResourceManager.GetString("home_section3_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10€ / month.
        /// </summary>
        public static string home_section3_lite_price {
            get {
                return ResourceManager.GetString("home_section3_lite_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Our basic rate for freelancers.
        /// </summary>
        public static string home_section3_lite_resume {
            get {
                return ResourceManager.GetString("home_section3_lite_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from €70 / month.
        /// </summary>
        public static string home_section3_pro_price {
            get {
                return ResourceManager.GetString("home_section3_pro_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan for companies with more than 10 professionals.
        /// </summary>
        public static string home_section3_pro_resume {
            get {
                return ResourceManager.GetString("home_section3_pro_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from €16 / month.
        /// </summary>
        public static string home_section3_pyme_price {
            get {
                return ResourceManager.GetString("home_section3_pyme_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rate for small companies (max.10 professionals).
        /// </summary>
        public static string home_section3_pyme_resume {
            get {
                return ResourceManager.GetString("home_section3_pyme_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Learn about our pricing plans.
        /// </summary>
        public static string home_section3_title {
            get {
                return ResourceManager.GetString("home_section3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you have any questions or want more information, contact us and an agent will contact you shortly..
        /// </summary>
        public static string home_section4_text {
            get {
                return ResourceManager.GetString("home_section4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact with us.
        /// </summary>
        public static string home_section4_title {
            get {
                return ResourceManager.GetString("home_section4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string langSpanish {
            get {
                return ResourceManager.GetString("langSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string login_btn_login {
            get {
                return ResourceManager.GetString("login_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        public static string login_btn_recoverPass {
            get {
                return ResourceManager.GetString("login_btn_recoverPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string login_email {
            get {
                return ResourceManager.GetString("login_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string login_pass {
            get {
                return ResourceManager.GetString("login_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show password.
        /// </summary>
        public static string login_seePass {
            get {
                return ResourceManager.GetString("login_seePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About NB.
        /// </summary>
        public static string menu_about {
            get {
                return ResourceManager.GetString("menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Associated centers.
        /// </summary>
        public static string menu_centers {
            get {
                return ResourceManager.GetString("menu_centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your health.
        /// </summary>
        public static string menu_health {
            get {
                return ResourceManager.GetString("menu_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Princing.
        /// </summary>
        public static string menu_pricing {
            get {
                return ResourceManager.GetString("menu_pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;An error has ocurred please try again later or contact us on hola@nutribuddy.com&quot;.
        /// </summary>
        public static string msgGeneralError {
            get {
                return ResourceManager.GetString("msgGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New patient.
        /// </summary>
        public static string paciente_titulo {
            get {
                return ResourceManager.GetString("paciente_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string recP_ChangePass {
            get {
                return ResourceManager.GetString("recP_ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received code on your email.
        /// </summary>
        public static string recP_Code {
            get {
                return ResourceManager.GetString("recP_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An email was sent to you with a code, enter the code here. Check your spam folder if you can not find it..
        /// </summary>
        public static string recP_CodeMsg {
            get {
                return ResourceManager.GetString("recP_CodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Come Back.
        /// </summary>
        public static string recP_ComeBack {
            get {
                return ResourceManager.GetString("recP_ComeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the registered email and press the button on the right. An email with a code will arrive..
        /// </summary>
        public static string recP_EmailMsg {
            get {
                return ResourceManager.GetString("recP_EmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string recP_NewPass {
            get {
                return ResourceManager.GetString("recP_NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        public static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to NutriBuddy.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nutribuddy allows nutritionists or multidisciplinary teams dedicated to improving health to connect with their patients quickly..
        /// </summary>
        public static string welcome_p1 {
            get {
                return ResourceManager.GetString("welcome_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In addition, the tool allows patients to have better control of their trajectory and their sessions..
        /// </summary>
        public static string welcome_p2 {
            get {
                return ResourceManager.GetString("welcome_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you want to take care of your health, we want to help you.
        /// </summary>
        public static string welcome_p3 {
            get {
                return ResourceManager.GetString("welcome_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you do not want to attend any of our centers, you can still use NutriBuddy as a journal of your progress..
        /// </summary>
        public static string welcome_p4 {
            get {
                return ResourceManager.GetString("welcome_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nutritional Diary.
        /// </summary>
        public static string welcome_p5 {
            get {
                return ResourceManager.GetString("welcome_p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to keep track of your eating habits? With NutriBuddy it is possible..
        /// </summary>
        public static string welcome_p6 {
            get {
                return ResourceManager.GetString("welcome_p6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register now, it is totally free, and you will be able to do a complete follow-up. You do not need to subscribe to any center to use the service..
        /// </summary>
        public static string welcome_p7 {
            get {
                return ResourceManager.GetString("welcome_p7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
