//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriBuddy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class trabajadores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal trabajadores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriBuddy.Resources.trabajadores", typeof(trabajadores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Employee.
        /// </summary>
        public static string cabecera_trabajador {
            get {
                return ResourceManager.GetString("cabecera_trabajador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string form_address {
            get {
                return ResourceManager.GetString("form_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI/NIE.
        /// </summary>
        public static string form_DNI {
            get {
                return ResourceManager.GetString("form_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string form_Email {
            get {
                return ResourceManager.GetString("form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        public static string form_Location {
            get {
                return ResourceManager.GetString("form_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacionality.
        /// </summary>
        public static string form_Nacionality {
            get {
                return ResourceManager.GetString("form_Nacionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string form_Name {
            get {
                return ResourceManager.GetString("form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telephone.
        /// </summary>
        public static string form_Phone {
            get {
                return ResourceManager.GetString("form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Positions.
        /// </summary>
        public static string form_Position {
            get {
                return ResourceManager.GetString("form_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social Security Number.
        /// </summary>
        public static string form_SS {
            get {
                return ResourceManager.GetString("form_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string form_State {
            get {
                return ResourceManager.GetString("form_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        public static string form_Surname {
            get {
                return ResourceManager.GetString("form_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Center Staff.
        /// </summary>
        public static string personal_msg_TC {
            get {
                return ResourceManager.GetString("personal_msg_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NutriBuddy Staff.
        /// </summary>
        public static string personal_msg_TNB {
            get {
                return ResourceManager.GetString("personal_msg_TNB", resourceCulture);
            }
        }
    }
}
